name: pr_swift_lint
on:
  pull_request_target:
    branches:
      - main
    types:
      - opened

jobs:
  swift_format_check:
    runs-on: macos-latest

    name: Run Swift Lint and Format Check

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Homebrew (if macOS does not have it)
        run: |
          if ! command -v brew &>/dev/null
          then
              /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        id: lint
        run: |
          swiftlint lint --config /Users/runner/work/Scribe-iOS/Scribe-iOS/.github/workflows/.swiftlint.yaml
          echo "::set-output name=exit_code::$?" # Capture the exit code of SwiftLint
        continue-on-error: true 

      - name: Run SwiftLint
        id: lint
        run: |
          swiftlint lint --config /Users/runner/work/Scribe-iOS/Scribe-iOS/.github/workflows/.swiftlint.yaml || true  # Ensure the command exits cleanly to allow capturing the exit code
          echo "exit_code=$?"  # Print it for debugging
          echo "::set-output name=exit_code::$?"  # Set the exit code as an output

