name: pr_swift_lint
on:
  pull_request_target:
    branches:
      - main
    types:
      - opened

jobs:
  swift_format_check:
    runs-on: macos-latest

    name: Run Swift Lint and Format Check

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Homebrew (if macOS does not have it)
        run: |
          if ! command -v brew &>/dev/null
          then
              /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: |
          swiftlint lint --config /Users/runner/work/Scribe-iOS/Scribe-iOS/.github/workflows/.swiftlint.yaml 
          exit_code=$?
          echo "SwiftLint Exit Code: $exit_code"
          if [ "$exit_code" -eq 0 ]; then
            echo "SwiftLint found no issues."
          elif [ "$exit_code" -eq 1 ]; then
            echo "SwiftLint found warnings."
            # Optionally handle warnings, e.g., do not fail the job
            echo "::set-output name=status::warning"
          elif [ "$exit_code" -eq 2 ]; then
            echo "SwiftLint found errors."
            echo "::set-output name=status::error"
            exit $exit_code  # Use the actual exit code from SwiftLint to fail the job
          else
            echo "Unexpected exit code: $exit_code"
            exit $exit_code  # Propagate unexpected exit code
          fi
        shell: bash
        id: swiftlint
