name: pr_swift_lint
on:
  pull_request_target:
    branches:
      - main
    types:
      - opened

jobs:
  swift_format_check:
    runs-on: macos-latest

    name: Run Swift Lint and Format Check

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Homebrew (if macOS does not have it)
        run: |
          if ! command -v brew &>/dev/null
          then
              /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        id: lint
        run: swiftlint lint --config /Users/runner/work/Scribe-iOS/Scribe-iOS/.github/workflows/.swiftlint.yaml
        continue-on-error: true 

      - name: Handle warnings
        if: ${{ steps.check_exit.outputs.status == 'warning' }}
        run: echo "Handling SwiftLint warnings."

      - name: Handle errors
        if: ${{ steps.check_exit.outputs.status == 'error' }}
        run: |
          echo "Errors detected by SwiftLint."
          exit 1

      - name: Success message
        if: ${{ steps.check_exit.outputs.status == 'success' }}
        run: echo "SwiftLint completed successfully without any issues."
