name: pr_swift_lint
on:
  pull_request_target:
    branches:
      - main
    types:
      - opened

jobs:
  swift_format_check:
    runs-on: macos-latest

    name: Run Swift Lint and Format Check

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Homebrew (if macOS does not have it)
        run: |
          if ! command -v brew &>/dev/null
          then
              /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: |
          swiftlint lint --reporter json --config /Users/runner/work/Scribe-iOS/Scribe-iOS/.github/workflows/.swiftlint.yaml 2>&1 | tee swiftlint-results.json
          warnings_count=$(jq '. | map(select(.severity == "Warning")) | length' swiftlint-results.json)
          errors_count=$(jq '. | map(select(.severity == "Error")) | length' swiftlint-results.json)
          
          if [ "$errors_count" -gt 0 ]; then
            echo "SwiftLint found errors." # Won't show message because exits immediatly
            exit 2
          elif [ "$warnings_count" -gt 0 ];
            echo "SwiftLint found warnings." # Can change message to be more reflective of what needs to be conveyed
            # exit 1         #Uncomment to enforce warnings
          else
            echo "SwiftLint found no issues." # Can change message to be more reflective of what needs to be conveyed
          fi
        shell: bash
